src/Entity/Customer.php
<?php

namespace App\Entity;

use DateTime;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * @ORM\Entity(repositoryClass="App\Repository\CustomerRepository")
 */
class Customer
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @Assert\NotBlank()
     * @ORM\Column(type="string", length=255)
     */
    private $name;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $firstname;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $fullAdress;

    /**
     * @ORM\Column(type="string", length=15)
     * @Assert\Regex(pattern="/^((\+)33|0|0033)[1-9](\d{2}){4}$/", message="Numéro invalide")
     */
    private $phone;

    /**
     * @ORM\Column(type="string", length=15, nullable=true)
     *
     */
    private $phone2;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     * Assert\Blank
     */
    private $mail;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $information;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\CustomerHeating", mappedBy="customer")
     */
    private $customerHeatings;

    /**
     * @ORM\Column(type="json_array", nullable=true)
     */
    private $coordGPS;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $city;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $department;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $region;

    /**
     * @ORM\Column(type="integer", nullable=true)
     */
    private $postalCode;

    /**
     * @ORM\Column(type="string", nullable=false)
     */
    private $complementAdress;

    /**
     * @ORM\Column(type="datetime", nullable=true)
     */
    private $contractDate;

    /**
     * @ORM\Column(type="integer", nullable=true)
     * @Assert\Range(
     *      min = 1,
     *      max = 12,
     *      minMessage = "You must be at least {{ limit }}cm tall to enter",
     *      maxMessage = "You cannot be taller than {{ limit }}cm to enter"
     * )
     */
    private $anniversaryDate;

    /**
     * @ORM\Column(type="boolean", nullable=true)
     */
    private $contractFinish;

    /**
     * @ORM\Column(type="datetime", nullable=true)
     */
    private $lastMaintenanceDate;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\InterventionReport", mappedBy="customer")
     */
    private $interventionReports;


    /**
     * not mapped
     *
     * @Assert\All({
     *     @Assert\Image(mimeTypesMessage="Ce fichier n'est pas une image valide", maxSize = "10M")
     * })
     */
    private $images;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Image", mappedBy="customer")
     */
    private $imagesLink;

    /**
     * @ORM\Column(type="datetime", nullable=true)
     */
    private $plannedMaintenanceDate;


    public function getFullname()
    {
        return $this->name . ' ' . $this->firstname;
    }

    public function makeAdress()
    {
        $this->fullAdress = $this->getComplementAdress() . ' ' . $this->getPostalCode() . ' ' . $this->getCity();
    }

    public function __construct()
    {
        $this->customerHeatings = new ArrayCollection();
        $this->interventionReports = new ArrayCollection();
        $this->imagesLink = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    public function getFirstname(): ?string
    {
        return $this->firstname;
    }

    public function setFirstname(string $firstname): self
    {
        $this->firstname = $firstname;

        return $this;
    }

    public function getPhone(): ?string
    {
        return $this->phone;
    }

    public function setPhone(string $phone): self
    {
        $this->phone = $phone;

        return $this;
    }

    public function getPhone2(): ?string
    {
        return $this->phone2;
    }

    public function setPhone2(?string $phone2): self
    {
        $this->phone2 = $phone2;

        return $this;
    }

    public function getMail(): ?string
    {
        return $this->mail;
    }

    public function setMail(?string $mail): self
    {
        $this->mail = $mail;

        return $this;
    }

    public function getInformation(): ?string
    {
        return $this->information;
    }

    public function setInformation(?string $information): self
    {
        $this->information = $information;

        return $this;
    }

    /**
     * @return Collection|CustomerHeating[]
     */
    public function getCustomerHeatings(): Collection
    {
        return $this->customerHeatings;
    }

    public function addCustomerHeating(CustomerHeating $customerHeating): self
    {
        if (!$this->customerHeatings->contains($customerHeating)) {
            $this->customerHeatings[] = $customerHeating;
            $customerHeating->setCustomer($this);
        }

        return $this;
    }

    public function removeCustomerHeating(CustomerHeating $customerHeating): self
    {
        if ($this->customerHeatings->contains($customerHeating)) {
            $this->customerHeatings->removeElement($customerHeating);
            // set the owning side to null (unless already changed)
            if ($customerHeating->getCustomer() === $this) {
                $customerHeating->setCustomer(null);
            }
        }

        return $this;
    }

    public function getCoordGPS()
    {
        return $this->coordGPS;
    }

    public function setCoordGPS($coordGPS): self
    {
        $this->coordGPS = $coordGPS;

        return $this;
    }

    public function getCity(): ?string
    {
        return $this->city;
    }

    public function setCity(?string $city): self
    {
        $this->city = $city;

        return $this;
    }

    public function getDepartment(): ?string
    {
        return $this->department;
    }

    public function setDepartment(?string $department): self
    {
        $this->department = $department;

        return $this;
    }

    public function getPostalCode(): ?int
    {
        return $this->postalCode;
    }

    public function setPostalCode(?int $postalCode): self
    {
        $this->postalCode = $postalCode;

        return $this;
    }

    public function getRegion(): ?string
    {
        return $this->region;
    }

    public function setRegion(?string $region): self
    {
        $this->region = $region;

        return $this;
    }

    /**
     * @return mixed
     */
    public function getFullAdress()
    {
        return $this->fullAdress;
    }

    /**
     * @param mixed $fullAdress
     */
    public function setFullAdress($fullAdress): void
    {
        $this->fullAdress = $fullAdress;
    }

    /**
     * @return mixed
     */
    public function getComplementAdress()
    {
        return $this->complementAdress;
    }

    /**
     * @param mixed $complementAdress
     */
    public function setComplementAdress($complementAdress): void
    {
        $this->complementAdress = $complementAdress;
    }

    public function getContractDate(): ?\DateTimeInterface
    {
        return $this->contractDate;
    }

    public function setContractDate(?\DateTimeInterface $contractDate): self
    {
        $this->contractDate = $contractDate;

        return $this;
    }

    public function getAnniversaryDate(): ?int
    {
        return $this->anniversaryDate;
    }

    public function setAnniversaryDate(?int $anniversaryDate): self
    {
        $this->anniversaryDate = $anniversaryDate;

        return $this;
    }

    public function getContractFinish(): ?bool
    {
        return $this->contractFinish;
    }

    public function setContractFinish(?bool $contractFinish): self
    {
        $this->contractFinish = $contractFinish;

        return $this;
    }

    public function getLastMaintenanceDate(): ?\DateTimeInterface
    {
        if($this->lastMaintenanceDate == null){
            return $this->getContractDate();
        }
        return $this->lastMaintenanceDate;
    }

    public function setLastMaintenanceDate(?\DateTimeInterface $lastMaintenanceDate): self
    {
        $this->lastMaintenanceDate = $lastMaintenanceDate;

        return $this;
    }

    /**
     * @return Collection|InterventionReport[]
     */
    public function getInterventionReports(): Collection
    {
        return $this->interventionReports;
    }

    public function addInterventionReport(InterventionReport $interventionReport): self
    {
        if (!$this->interventionReports->contains($interventionReport)) {
            $this->interventionReports[] = $interventionReport;
            $interventionReport->setCustomer($this);
        }

        return $this;
    }

    public function removeInterventionReport(InterventionReport $interventionReport): self
    {
        if ($this->interventionReports->contains($interventionReport)) {
            $this->interventionReports->removeElement($interventionReport);
            // set the owning side to null (unless already changed)
            if ($interventionReport->getCustomer() === $this) {
                $interventionReport->setCustomer(null);
            }
        }

        return $this;
    }

    /**
     * @return mixed
     */
    public function getPlannedMaintenanceDate(): ?DateTime
    {
        return $this->plannedMaintenanceDate;
    }

    /**
     * @param mixed $plannedMaintenanceDate
     */
    public function setPlannedMaintenanceDate(DateTime $plannedMaintenanceDate): void
    {

src/Form/InterventionReportType.php
<?php

namespace App\Form;

use App\Entity\InterventionReport;
use App\Entity\TypeInterventionReport;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;
use Symfony\Component\Form\Extension\Core\Type\DateType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class InterventionReportType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('plannedOrRealised', ChoiceType::class, [
                'mapped' => false,
                'choices' => [
                    'Plannifié' => false,
                    'Réalisé' => true,
                ],
                'expanded' => true,
                'multiple' => false,
                'required'=>true,
                'data' => false,
            ])
            ->add('dateForSelected', DateType::class, [
                'label' => 'Date',
                'widget' => 'single_text',
                'mapped' => false,
                'required' => true,
                ])
            ->add('comment')
//            ->add('typeInterventionReport', EntityType::class, [
//                'label' => 'Type d\'intervention',
//                'class' => TypeInterventionReport::class,
//                'choice_label' => 'name',
//                'attr' => ['class' => 'text-capitalize'],
//            ])
            ->add('typeInterventionReport',ChoiceType::class,[
                'choices' => InterventionReport::CHOICE,

            ]);
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => InterventionReport::class,
        ]);
    }
}

src/Controller/InterventionReportController.php
<?php

namespace App\Controller;

use App\Entity\Customer;
use App\Entity\InterventionReport;
use App\Form\InterventionReportEditType;
use App\Form\InterventionReportType;
use App\Repository\InterventionReportRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
 * @Route("/intervention/report")
 */
class InterventionReportController extends AbstractController
{
    /**
     * @param InterventionReportRepository $interventionReportRepository
     * @param Customer $customer
     * @return Response
     * @Route("/{customer}", name="intervention_report_list", methods="GET")
     */
    public function index(InterventionReportRepository $interventionReportRepository, Customer $customer): Response
    {
        return $this->render('intervention_report/index.html.twig',
            [
                'intervention_reports' => $interventionReportRepository->findByCustomer($customer),
                'customer' => $customer
            ]);
    }

    /**
     * @param Request $request
     * @param Customer $customer
     * @return Response
     * @Route("/new/{customer}", name="intervention_report_new", methods="GET|POST")
     */
    public function new(Request $request, Customer $customer): Response
    {
        $interventionReport = new InterventionReport();
        $form = $this->createForm(InterventionReportType::class, $interventionReport);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $interventionReport->setCustomer($customer);
            $plannedOrRealised = $form->get('plannedOrRealised')->getViewData();
            // si planifié ou realisé selectionné, on set la date du param correspondant
            $plannedOrRealised ? $interventionReport->setRealisedDate($form->get('dateForSelected')->getNormData()) :
                $interventionReport->setPlannedDate($form->get('dateForSelected')->getNormData());
            $em = $this->getDoctrine()->getManager();
            $em->persist($interventionReport);
            $em->flush();

            // mise à jour du plannedMaintenanceDate du client
            $customer->setPlannedMaintenanceDate($interventionReport->getPlannedDate());
            $em->persist($customer);
            $em->flush();

            return $this->redirectToRoute('intervention_report_list', ['customer' => $customer->getId()]);
        }

        return $this->render('intervention_report/new.html.twig', [
            'intervention_report' => $interventionReport,
            'customerId' => $customer->getId(),
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/show/{id}", name="intervention_report_show", methods="GET")
     */
    public function show(InterventionReport $interventionReport): Response
    {
        return $this->render('intervention_report/show.html.twig', ['intervention_report' => $interventionReport]);
    }

    /**
     * @Route("/{id}/edit", name="intervention_report_edit", methods="GET|POST")
     */
    public function edit(Request $request, InterventionReport $interventionReport): Response
    {
        $form = $this->createForm(InterventionReportEditType::class, $interventionReport);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $this->getDoctrine()->getManager()->flush();

            // si maintenance à été modifié
            if($interventionReport->getTypeInterventionReport() == "maintenance" &&
                $interventionReport->getCustomer()->getPlannedMaintenanceDate() != $interventionReport->getPlannedDate()){
                $em = $this->getDoctrine()->getManager();
                /** @var Customer $customer */
                $customer = $interventionReport->getCustomer();
                $customer->setPlannedMaintenanceDate($interventionReport->getPlannedDate());
                $em->persist($customer);
                $em->flush();
            }

            // si status à été modifié en réalisé


            // si status à été modifié en plannifié
            

            return $this->redirectToRoute('intervention_report_list', ['customer' => $interventionReport->getCustomer()->getId()]);
        }
        dump($interventionReport);
        return $this->render('intervention_report/edit.html.twig', [
            'intervention_report' => $interventionReport,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="intervention_report_delete", methods="DELETE")
     */
    public function delete(Request $request, InterventionReport $interventionReport): Response
    {
        if ($this->isCsrfTokenValid('delete' . $interventionReport->getId(), $request->request->get('_token'))) {
            $em = $this->getDoctrine()->getManager();
            $em->remove($interventionReport);
            $em->flush();
        }

        return $this->redirectToRoute('intervention_report_index');
    }
}

templates/intervention_report/_delete_form.html.twig
<form method="post" action="{{ path('intervention_report_delete', {'id': intervention_report.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_method" value="DELETE">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ intervention_report.id) }}">
    <button class="btn btn-outline-danger">Supprimer</button>
</form>

templates/intervention_report/_form.html.twig
{{ form_start(form) }}
{% if(form.plannedOrRealised is defined) %}
    <div class="row">
        <div class="col">
            {{ form_widget(form.plannedOrRealised , {'attr':{'class':'form-check-inline mb-3' }}) }}
        </div>
    </div>
{% endif %}
<div class="row">
    {% if(form.dateForSelected is defined) %}
        {% set dateNow = "now"|date("m-d-Y")  %}
        <div class="col-sm-4">
            {{ form_label(form.dateForSelected) }}
            {{ form_widget(form.dateForSelected , {'attr':{'class':'mb-3' }}) }}
        </div>
    {% endif %}
    {% if(form.plannedDate is defined) %}
        <div class="col-sm-4">
            {{ form_label(form.plannedDate) }}
            {{ form_widget(form.plannedDate , {'attr':{'class':'mb-3' }}) }}
        </div>
    {% endif %}
    {% if(form.realisedDate is defined) %}
        <div class="col-sm-4">
            {{ form_label(form.realisedDate) }}
            {{ form_widget(form.realisedDate , {'attr':{'class':'mb-3' }}) }}
        </div>
    {% endif %}
    <div class="col-sm-4">
        {{ form_label(form.typeInterventionReport) }}
        {{ form_widget(form.typeInterventionReport , {'attr':{'class':'mb-3' }}) }}
    </div>
</div>
{{ form_label(form.comment) }}
{{ form_widget(form.comment,{'attr':{'rows':10 ,class : 'mb-3'}}) }}
<div class="row">
    <div class="col text-center">
        <button class="btn btn-primary">{{ button_label|default('Ajouter') }}</button>
    </div>
</div>
{{ form_end(form) }}

templates/intervention_report/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit InterventionReport{% endblock %}

{% block body %}
<div class="container">
    <h1>Modification du rapport d'intervention</h1>
    <h5 class="text-center"><span class="badge badge-info">{{ intervention_report.customer.fullname }}</span></h5>
    <div class="row">
        <div class="col text-right">
            {{ include('intervention_report/_delete_form.html.twig') }}
        </div>
    </div>

    {{ include('intervention_report/_form.html.twig', {'button_label': 'Valider'}) }}

    <a class="btn btn-outline-info"
       href="{{ path('intervention_report_list',{'customer': intervention_report.customer.id} ) }}">Retour</a>

</div>
    {% endblock %}

templates/intervention_report/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}InterventionReport index{% endblock %}

{% block body %}
    <div class="container">
        <div class="row">
            <div class="col">
                <h1>Rapport d'interventions</h1>
            </div>
        </div>
        <div class="row">
            <div class="col">
                <table class="table text-center">
                    <thead>
                    <tr>
                        <th>Type d'intervention</th>
                        <th>Date plannifié</th>
                        <th>Date de réalisation</th>
                        <th>actions</th>
                    </tr>
                    </thead>
                    <tbody>
                    {% for intervention_report in intervention_reports %}
                        <tr>
                            <td>{{ intervention_report.typeInterventionReport }}</td>
                            <td>{{ intervention_report.plannedDate ? intervention_report.plannedDate|date('d M Y') : '' }}</td>
                            <td>{{ intervention_report.realisedDate ? intervention_report.realisedDate|date('d M Y') : '' }}</td>
                            <td>

                                <a href="{{ path('intervention_report_edit', {'id': intervention_report.id}) }}"><img
                                            class="icone" src="/img/edit.png"></a>
                            </td>
                        </tr>
                    {% else %}
                        <tr>
                            <td colspan="5">Aucune intervention trouvée</td>
                        </tr>
                    {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
        <div class="row">
            <div class="col d-flex justify-content-between ">
                <a class="d-inline-block btn btn-outline-info" href="{{ path('customer_show',{'id': customer.id}) }}">Retour</a>
                <a class="d-inline-block btn btn-primary" href="{{ path('intervention_report_new', {'customer': customer.id}) }}">Ajouter</a>
            </div>
        </div>
    </div>
{% endblock %}

templates/intervention_report/list.html.twig
{% extends 'base.html.twig' %}

{% block title %}InterventionReport index{% endblock %}

{% block body %}
    <h1>Historique de rapport d'intervention: {{ intervention_report.customer.fullname }}</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>PlannedDate</th>
                <th>RealisedDate</th>
                <th>Comment</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for intervention_report in intervention_reports %}
            <tr>
                <td>{{ intervention_report.id }}</td>
                <td>{{ intervention_report.plannedDate ? intervention_report.plannedDate|date('Y-m-d H:i:s') : '' }}</td>
                <td>{{ intervention_report.realisedDate ? intervention_report.realisedDate|date('Y-m-d H:i:s') : '' }}</td>
                <td>{{ intervention_report.comment }}</td>
                <td>
                    <a href="{{ path('intervention_report_show', {'id': intervention_report.id}) }}">show</a>
                    <a href="{{ path('intervention_report_edit', {'id': intervention_report.id}) }}">edit</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="5">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('intervention_report_new', {'customerId': customer.id}) }}">Create new</a>
{% endblock %}

templates/intervention_report/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New InterventionReport{% endblock %}

{% block body %}
    <div class="container">
    <h1>Nouvelle intervention</h1>

    {{ include('intervention_report/_form.html.twig') }}

    <a class="btn btn-outline-info" href="{{ path('intervention_report_list', {'customer': customerId}) }}">Retour</a>
    </div>
{% endblock %}

templates/intervention_report/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}InterventionReport{% endblock %}

{% block body %}
    <div class="container">
        <h1 class="mb-4">InterventionReport</h1>
        <div class="text-right mb-2">
        {{ include('intervention_report/_delete_form.html.twig') }}
        </div>

        <div class="row">
            <div class="col-lg-6 mx-auto">
                <table class="table table-condensed">
                    <tbody>
                    <tr>
                        <th class="w-50 p-2">Type d'intervention</th>
                        <td class="p-2">{{ intervention_report.typeInterventionReport.name }}</td>
                    </tr>
                    <tr>
                        <th class="w-50 p-2">Date plannifiée</th>
                        <td class="p-2">{{ intervention_report.plannedDate ? intervention_report.plannedDate|date('d M Y') : '' }}</td>
                    </tr>
                    <tr>
                        <th class="w-50 p-2">Date de réalisation</th>
                        <td class="p-2">{{ intervention_report.realisedDate ? intervention_report.realisedDate|date('d M Y') : '' }}</td>
                    </tr>
                    </tbody>
                </table>
            </div>
        </div>
        <div class="row">
            <div class="col">
                <table class="table">
                    <tbody>
                    <tr>
                        <th class="text-center">Commentaire</th>
                    </tr>
                    <tr>
                        <td>{{ intervention_report.comment }}</td>
                    </tr>
                    </tbody>
                </table>
            </div>
        </div>
        <div class="d-flex justify-content-between">
            <a class="btn btn-outline-info" href="{{ path('intervention_report_list',{'customer': intervention_report.customer.id} ) }}">Retour</a>
            <a class="btn btn-primary" href="{{ path('intervention_report_edit', {'id': intervention_report.id}) }}">Valider</a>
        </div>


    </div>
{% endblock %}